"""memos-graph configuration."""

import os
from pathlib import Path
from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict


def get_default_config() -> str:
    """Return default config YAML."""
    return """# memos-graph configuration
# Generated by `memos-graph init`

server:
  host: 127.0.0.1
  port: 8765

database:
  url: postgresql+asyncpg://memos:memos@localhost:5432/memos_graph
  pool_size: 10
  pool_recycle: 3600

embedding:
  provider: ollama
  model: nomic-embed-text
  dimension: 768
  base_url: http://localhost:11434
  cache_db: ~/.local/share/memos-graph/embeddings.db
  timeout_seconds: 30

llm:
  base_url: https://maas-coding-api.cn-huabei-1.xf-yun.com/v1
  api_key: ${ANTHROPIC_API_KEY}
  model: astron-code-latest
  timeout_seconds: 60

viewer:
  enabled: true
  host: 127.0.0.1
  port: 8080

logging:
  level: INFO
  format: json
  file: ~/.local/share/memos-graph/logs/daemon.log
  rotation: "10 MB"
"""


def get_config_dir() -> Path:
    """Get config directory path."""
    xdg_config = os.environ.get("XDG_CONFIG_HOME", "~/.config")
    return Path(xdg_config).expanduser() / "memos-graph"


def ensure_config_dir() -> Path:
    """Ensure config directory exists."""
    config_dir = get_config_dir()
    config_dir.mkdir(parents=True, exist_ok=True)
    return config_dir


def get_data_dir() -> Path:
    """Get data directory path."""
    xdg_data = os.environ.get("XDG_DATA_HOME", "~/.local/share")
    return Path(xdg_data).expanduser() / "memos-graph"


def ensure_data_dir() -> Path:
    """Ensure data directory exists."""
    data_dir = get_data_dir()
    data_dir.mkdir(parents=True, exist_ok=True)
    return data_dir


def get_log_dir() -> Path:
    """Get log directory path."""
    return ensure_data_dir() / "logs"


def ensure_log_dir() -> Path:
    """Ensure log directory exists."""
    log_dir = get_log_dir()
    log_dir.mkdir(parents=True, exist_ok=True)
    return log_dir


def get_packs_dir() -> Path:
    """Get packs directory path."""
    return ensure_data_dir() / "packs"


def ensure_packs_dir() -> Path:
    """Ensure packs directory exists."""
    packs_dir = get_packs_dir()
    packs_dir.mkdir(parents=True, exist_ok=True)
    return packs_dir


class DatabaseSettings(BaseSettings):
    """Database settings."""
    url: str = Field(default="postgresql+asyncpg://memos:memos@localhost:5432/memos_graph")
    pool_size: int = Field(default=10)
    pool_recycle: int = Field(default=3600)

    model_config = SettingsConfigDict(env_prefix="MEMOS_DB_")


class EmbeddingSettings(BaseSettings):
    """Embedding settings."""
    provider: str = Field(default="siliconflow")
    model: str = Field(default="BAAI/bge-m3")
    dimension: int = Field(default=1024)
    base_url: str = Field(default="https://api.siliconflow.cn/v1")
    api_key: str = Field(default="")
    cache_db: str = Field(default="~/.local/share/memos-graph/embeddings.db")
    timeout_seconds: int = Field(default=30)

    model_config = SettingsConfigDict(env_prefix="MEMOS_EMBEDDING_", extra="ignore")


class LLMSettings(BaseSettings):
    """LLM settings (35B infinite calls)."""
    base_url: str = Field(default="https://maas-coding-api.cn-huabei-1.xf-yun.com/v1")
    api_key: str = Field(default="")
    model: str = Field(default="astron-code-latest")
    timeout_seconds: int = Field(default=60)

    model_config = SettingsConfigDict(env_prefix="MEMOS_LLM_")


class Neo4jSettings(BaseSettings):
    """Neo4j settings."""
    uri: str = Field(default="bolt://localhost:7687")
    username: str = Field(default="neo4j")
    password: str = Field(default="memos2024")

    model_config = SettingsConfigDict(env_prefix="MEMOS_NEO4J_")


class ServerSettings(BaseSettings):
    """Server settings."""
    host: str = Field(default="127.0.0.1")
    port: int = Field(default=8765)

    model_config = SettingsConfigDict(env_prefix="MEMOS_SERVER_")


class ViewerSettings(BaseSettings):
    """Viewer settings."""
    enabled: bool = Field(default=True)
    host: str = Field(default="127.0.0.1")
    port: int = Field(default=8080)

    model_config = SettingsConfigDict(env_prefix="MEMOS_VIEWER_")


class LoggingSettings(BaseSettings):
    """Logging settings."""
    level: str = Field(default="INFO")
    format: str = Field(default="json")
    file: str = Field(default="~/.local/share/memos-graph/logs/daemon.log")
    rotation: str = Field(default="10 MB")

    model_config = SettingsConfigDict(env_prefix="MEMOS_LOGGING_")


class Config(BaseSettings):
    """Main configuration."""
    database: DatabaseSettings = Field(default_factory=DatabaseSettings)
    embedding: EmbeddingSettings = Field(default_factory=EmbeddingSettings)
    llm: LLMSettings = Field(default_factory=LLMSettings)
    neo4j: Neo4jSettings = Field(default_factory=Neo4jSettings)
    server: ServerSettings = Field(default_factory=ServerSettings)
    viewer: ViewerSettings = Field(default_factory=ViewerSettings)
    logging: LoggingSettings = Field(default_factory=LoggingSettings)

    model_config = SettingsConfigDict(env_prefix="MEMOS_", extra="ignore")


def load_config(config_path: Path | None = None) -> Config:
    """Load configuration from file or environment."""
    if config_path is None:
        config_path = get_config_dir() / "config.yaml"

    if config_path.exists():
        import yaml
        with open(config_path) as f:
            data = yaml.safe_load(f)
        return Config(**data)

    return Config()
